AllCops:
  AutoCorrect: true
Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
Style/ConditionalAssignment:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/Documentation:
  Enabled: false
